# Generated by Django 2.2.4 on 2023-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='title',
        ),
        migrations.AddField(
            model_name='ninja',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ninja',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
